version: "3.7"
services:

  ### Laravel Container 
  wcos-backend:
    image: wcos/marketplace-backend:latest
    container_name: wcos-backend
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - wcos-network

 ### Database Container (Mysql)
  wcos-db:
    image: mysql:5.7
    container_name: wcos-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'wcos'
      MYSQL_ROOT_PASSWORD: 'changeme'
      MYSQL_PASSWORD: 'changeme'
      MYSQL_USER: 'wcos'
      
    volumes:
      - "./deploy/wcos-dump.sql:/docker-entrypoint-initdb.d/wcos-dump.sql"
      # - "./db-data:/var/lib/mysql"
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - wcos-network

### Nginx Container
  wcos-nginx:
    image: nginx:alpine
    container_name: wcos-nginx
    restart: unless-stopped
    ports:
    ### Project is configured to allow serving under a reverse proxies
    ### in such cases, you would need to only expose the http line while
    ### allowing the reverse proxy handle the ssl connection between users and the server.    
      - 2222:80
    ### if deploying for production without reverse-proxy uncomment below and comment '2222:80' above.
      # - 80:80
      # - 443:443
    volumes:
      - ./:/var/www
      - ./deploy/wcos-nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wcos-network

networks:
  wcos-network:
    driver: bridge